version: '3.8'

services:
  app:
    image: almeidasnp/camara-gestao:latest
    container_name: camara_gestao_prod
    restart: always
    ports:
      - "80:8080" # Acessível na porta 80 (HTTP padrão)
    volumes:
      - ./data:/app/data # Persistência do banco de dados e backups
    environment:
      - DB_PATH=/app/data/glpi_clone.db
      - BACKUP_DIR=/app/data/backups
      - PORT=8080
      - GIN_MODE=release
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/debug/users" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
